global:
  version: '2025.6.9'
  labels:
    app: sschool
    team: vaam-store

defaultPodOptions:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001

controllers:
  main:
    type: deployment
    replicas: 2
    labels:
      main: main-app
    initContainers:
      migrations:
        image:
          repository: ghcr.io/vaam-store/sschool-migrations
          tag: '{{ .Values.global.version }}'
          pullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              identifier: db

        resources:
          requests:
            cpu: 125m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
    containers:
      app:
        image:
          repository: ghcr.io/vaam-store/sschool
          tag: '{{ .Values.global.version }}'
          pullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 125m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi

        # -- ConfigMap to be loaded as environment variables
        envFrom:
          - configMapRef:
              identifier: config
          - configMapRef:
              identifier: otel
          - configMapRef:
              identifier: redis
          - secretRef:
              identifier: s3
          - secretRef:
              identifier: auth
          - secretRef:
              identifier: db
          - secretRef:
              identifier: redis
          - secretRef:
              identifier: ai

service:
  app:
    enabled: true
    annotations: { }
    nameOverride: service
    type: ClusterIP
    controller: main
    ports:
      http:
        enabled: true
        port: 3000
        targetPort: 3000

ingress:
  app:
    enabled: true
    annotations: { }
    nameOverride: ingress
    #className: 'nginx'
    hosts:
      - host: sschool.example.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - secretName: sschool-example-com-secret
        hosts:
          - sschool.example.com

configMaps:
  config:
    enabled: true
    annotations:
      description: 'Common configuration for the SSchool.'
    data:
      AUTH_KEYCLOAK_ISSUER: https://kec.example.com/realms/main
      NEXT_PUBLIC_EMGR_CDN: https://emgr.example.com/api/images/resize

      AUTH_SESSION_MAX_AGE: '2592000'
      AUTH_SESSION_UPDATE_AGE: '2592000'

      S3_ENDPOINT: s3.example.com
      S3_PORT: '443'
      S3_SCHEME: https
      S3_BUCKET: sschool
      S3_CDN_URL: https://s3.example.com
  otel:
    enabled: true
    annotations:
      description: 'OTEL configuration for the SSchool.'
    data:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'https://otel.example.com'
  redis:
    enabled: true
    annotations:
      description: 'Redis configuration for the SSchool.'
    data:
      REDIS_PREFIX: 'sschool_'

secrets:
  s3:
    enabled: true
    annotations:
      description: 'S3 configuration for the SSchool.'
    stringData:
      S3_ACCESS_KEY: 'minio'
      S3_SECRET_KEY: 'minio123'
  smtp:
    enabled: true
    annotations:
      description: 'SMTP configuration for the SSchool.'
    stringData:
      SMTP_URL: 'smtp+ssl://user:password@smtp.example:582'
  auth:
    enabled: true
    annotations:
      description: 'Auth configuration for the SSchool.'
    stringData:
      AUTH_SECRET: 'gfhZ+94pqhGDi03RCD/6klIbTd92V5yA8G+oEN9c6pk='
      AUTH_KEYCLOAK_ID: 'sschool'
      AUTH_KEYCLOAK_SECRET: 'someSecret'
  db:
    enabled: true
    annotations:
      description: 'Auth configuration for the SSchool.'
    stringData:
      DATABASE_URL: 'postgresql+ssl://gisapply:gisapply-password@localhost:5432/gisapply?schema=public'
  redis:
    enabled: true
    annotations:
      description: 'Redis configuration for the SSchool.'
    stringData:
      REDIS_URL: 'redis://${redis_host}:${redis_port}'
  ai:
    enabled: true
    annotations:
      description: 'AI configuration for the SSchool.'
    stringData:
      OPENAI_KEY: ''
      OPENAI_URL: ''

      OPENAI_MAX_TOKENS: '1000'
      OPENAI_PAGE_DESCRIPTION_MAX_TOKEN: '50'
      OPENAI_PAGE_LAYOUT_MODEL: 'gpt-4o'
      OPENAI_PAGE_CONTENT_MODEL: 'gemini-2.0-flash-lite'

