apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.name" $ }}-pdb
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{ include "common.annotations.standard" (dict "rootContext" $ "controllerObject" $.Values.controllers) | nindent 4 }}
  labels:
    {{ include "bjw-s.common.lib.pod.metadata.labels" (dict "rootContext" $ "controllerObject" $.Values.controllers) | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{ include "bjw-s.common.lib.metadata.selectorLabels" $ | nindent 6 }}
