name: Helm Publish

on:
  push:
    branches:
      - '*' # Matches all branches
    tags:
      - 'v*'
    paths:
      - 'charts/**'
      - '.github/workflows/deploy-docs.yml'

permissions:
  contents: write
  packages: write # Required for pushing to GHCR

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Helm Chart Steps
      - name: Configure Git
        # This step is generally good practice before actions that commit,
        # though chart-releaser-action might handle its own git config.
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        # No explicit GITHUB_TOKEN env var needed here for azure/setup-helm.

      - name: Cache Helm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/helm
          key: ${{ runner.os }}-helm-${{ hashFiles('**/Chart.yaml') }}
          restore-keys: |
            ${{ runner.os }}-helm-

      - name: Add Helm repositories
        # This step was in the original 'deploy-helm-chart.yml'.
        # Include this if your charts in the 'helm/' directory have dependencies
        # on charts from 'bjw-s' that need to be resolved during packaging.
        # If your charts are self-contained or manage dependencies differently,
        # this step might be adjusted or removed.
        run: |
          helm repo add bjw-s https://bjw-s-labs.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts # Specifies the directory containing your Helm charts.
          # The chart-releaser-action handles checking out the gh-pages branch,
          # packaging charts, updating the index.yaml, committing, and pushing.
          # It is designed to be additive to the gh-pages branch.